// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: email.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getEmailByUUID = `-- name: GetEmailByUUID :one
SELECT recipient, subject, send_date, uuid FROM email WHERE uuid = $1
`

func (q *Queries) GetEmailByUUID(ctx context.Context, argUuid uuid.UUID) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByUUID, argUuid)
	var i Email
	err := row.Scan(
		&i.Recipient,
		&i.Subject,
		&i.SendDate,
		&i.Uuid,
	)
	return i, err
}

const getEmails = `-- name: GetEmails :many
SELECT recipient, subject, send_date, uuid FROM email
`

func (q *Queries) GetEmails(ctx context.Context) ([]Email, error) {
	rows, err := q.db.Query(ctx, getEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.Recipient,
			&i.Subject,
			&i.SendDate,
			&i.Uuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailsWithPagination = `-- name: GetEmailsWithPagination :many
SELECT recipient, subject, send_date, uuid FROM email ORDER BY send_date DESC LIMIT $1 OFFSET $2
`

type GetEmailsWithPaginationParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetEmailsWithPagination(ctx context.Context, arg GetEmailsWithPaginationParams) ([]Email, error) {
	rows, err := q.db.Query(ctx, getEmailsWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.Recipient,
			&i.Subject,
			&i.SendDate,
			&i.Uuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEmail = `-- name: InsertEmail :one
INSERT INTO email (recipient, subject) VALUES ($1, $2) RETURNING recipient, subject, send_date, uuid
`

type InsertEmailParams struct {
	Recipient string
	Subject   string
}

func (q *Queries) InsertEmail(ctx context.Context, arg InsertEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, insertEmail, arg.Recipient, arg.Subject)
	var i Email
	err := row.Scan(
		&i.Recipient,
		&i.Subject,
		&i.SendDate,
		&i.Uuid,
	)
	return i, err
}
