// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Email struct {
	Recipient string
	Subject   string
	SendDate  time.Time
	Uuid      uuid.UUID
}

type Tracker struct {
	TrackerID int32
	OpenDate  time.Time
	EmailUuid uuid.UUID
	IpAddress *string
}
