// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "dev"
//go:build !wireinject
// +build !wireinject

package services

import (
	"github.com/corentings/email-tracker/app/handlers"
	"github.com/corentings/email-tracker/pkg/postgres"
	"github.com/corentings/email-tracker/services/email"
)

// Injectors from wire.go:

func InitializeEmailHandler() handlers.EmailController {
	pool := postgres.GetPool()
	iUseCase := email.NewUseCase(pool)
	emailController := handlers.NewEmailController(iUseCase)
	return emailController
}

func InitializeJwtMiddleware() handlers.JwtMiddleware {
	jwtMiddleware := handlers.NewJwtMiddleware()
	return jwtMiddleware
}
